name: Install Deno and Execute Commands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create .pgpass file
        run: |
          echo "${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}:${{ secrets.DB_NAME }}:${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}" > ~/.pgpass
          chmod 600 ~/.pgpass

      - name: Clone Polyglot Prime repository
        run: git clone https://github.com/tech-by-design/polyglot-prime.git

      - name: Navigate to UDI Prime and Generate SQL
        run: |
          cd polyglot-prime/udi-prime
          ./udictl.ts ic generate sql 

      - name: Run Migrations
        run: |
          cd polyglot-prime/udi-prime
          ./udictl.ts ic migrate --destroy-first --conn-id MY_SANDBOX_2
