name: Install Deno and Execute Commands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo 'export DENO_INSTALL="$HOME/.deno"' >> $GITHUB_ENV
          echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> $GITHUB_ENV
          export DENO_INSTALL="$HOME/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"

      - name: Get SQL-Aide Version
        id: get-sqla-version
        run: |
          SQLa_VERSION=$(curl -fsSL https://api.github.com/repos/netspective-labs/sql-aide/tags | jq '.[0].name' -r)
          echo "SQLa_VERSION=$SQLa_VERSION" >> $GITHUB_ENV

      - name: Install SQL-Aide
        run: |
          SQLa_VERSION=${{ env.SQLa_VERSION }}
          deno install -A -f https://raw.githubusercontent.com/netspective-labs/sql-aide/${SQLa_VERSION}/lib/postgres/pgpass/pgpass.ts

      - name: Create .pgpass file
        run: |
          echo "${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}:${{ secrets.DB_NAME }}:${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}" > ~/.pgpass
          chmod 600 ~/.pgpass

      - name: Clone Polyglot Prime repository
        run: git clone https://github.com/tech-by-design/polyglot-prime.git

      - name: Navigate to UDI Prime and Generate SQL
        run: |
          cd polyglot-prime/udi-prime
          ./udictl.ts ic generate sql 

      - name: Run Migrations
        run: |
          cd polyglot-prime/udi-prime
          ./udictl.ts ic migrate --destroy-first --conn-id MY_SANDBOX_2
